## Numpy 설치
> !pip install numpy

## 패키지 불러오기
>import numpy as np

## 코랩 사용

>shift + enter 코드 실행

In [ ]:
!pip install numpy

Requirement already satisfied: numpy in /usr/local/lib/python3.10/dist-packages (1.25.2)

In [ ]:
import numpy as np

test_array = np.array([1,4,5,8], float)
test_array

array([1., 4., 5., 8.])

In [ ]:
print('안녕하세요')

안녕하세요

#**Numpy**

##1. NumPy(넘파이) 특징
####(1) 과학 계산을 위한 라이브러리
####(2) 행렬/배열 처리 및 연산
####(3) 난수생성
##2. 배열의 생성
####(1) 리스트에서 행렬/ 배열 생성

In [ ]:
import numpy as np # numpy 패키지 로드하여 np로 사용

a = [[1,2,3], [4,5,6]] # 리스트에서 행렬생성
b = np.array(a)
print(b)

[[1 2 3]
 [4 5 6]]

In [ ]:
print(b.ndim)  # 배열의 열수(차원)

2

In [ ]:
print(b.shape) # 배열의 차원

(2, 3)

In [ ]:
print(b[0,0])  # 배열의 원소 접근

1

##2. 특수한 배열의 생성

In [ ]:
print(np.arange(10)) # 1씩 증가하는 1차원 배열(시작이 0부터)

[0 1 2 3 4 5 6 7 8 9]

In [ ]:
print(np.arange(5, 10)) # 1씩 증가하는 1차원 배열(시작이 5부터)

[5 6 7 8 9]

In [ ]:
print(np.zeros((2,2)))  # 영행렬 생성

[[0. 0.]
 [0. 0.]]

In [ ]:
print(np.ones((2,3)))  # 유닛행렬

[[1. 1. 1.]
 [1. 1. 1.]]

In [ ]:
print(np.full((2,3), 5)) # 모든 원소가 5인 2*3행렬

[[5 5 5]
 [5 5 5]]

In [ ]:
print(np.eye(3)) # 단위행렬

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

In [ ]:
import numpy as np
arr=np.linspace(0,100,20) # 0~100사이 20개를 선택
print(arr)

[  0.           5.26315789  10.52631579  15.78947368  21.05263158
  26.31578947  31.57894737  36.84210526  42.10526316  47.36842105
  52.63157895  57.89473684  63.15789474  68.42105263  73.68421053
  78.94736842  84.21052632  89.47368421  94.73684211 100.        ]

In [ ]:
arr.dtype

dtype('float64')

In [ ]:
arr.astype(np.int32)
arr[15]

78.94736842105263

##3. 배열의 차원

In [ ]:
a = np.arange(20) #1씩 증가하는 1차원 배열
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]

In [ ]:
b=a.reshape((4,5)) #차원 변경, 1차원 배열을 2차원 배열로
print(b)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]

In [ ]:
print(np.zeros((2,2))) #0행렬 생성

[[0. 0.]
 [0. 0.]]

In [ ]:
print(np.ones((2,2))) #1행렬 생성

[[1. 1.]
 [1. 1.]]

In [ ]:
print(np.full((2,2),5)) #2*2행렬을 만드는데 5로 채워서 만듬

[[5 5]
 [5 5]]

In [ ]:
print(np.eye(3)) #단위행렬

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

##3.Numpy 슬라이싱/**인덱싱**

In [ ]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
arr[5]

5

In [ ]:
arr[5:8]

array([5, 6, 7])

In [ ]:
# 배열 슬라이스는 새로운 객체를 만드는 것이 아닌 원래 배열에 대한 뷰(view)임. 즉 선택 부분의 값을 변경하면 원래 배열으리 같은 위치의 값도 번경되는 것
arr[5:8]=10
arr

array([ 0,  1,  2,  3,  4, 10, 10, 10,  8,  9])

In [ ]:
arr_slice=arr[5:8]
arr_slice

array([10, 10, 10])

In [ ]:
# 다음과 같이 arr_slice의 부분을 변경하면 원래 배열 arr도 값이 변경된 것을 알 수 있다

arr_slice[1]=1234
arr_slice

array([  10, 1234,   10])

In [ ]:
arr

array([   0,    1,    2,    3,    4,   10, 1234,   10,    8,    9])

In [ ]:
# 시작과 끝이 없는 슬라이싱은 모든 원소를 선택하는 것이기 때문에 다음은 모든 값을 변경
arr_slice[:]=500
arr

array([  0,   1,   2,   3,   4, 500, 500, 500,   8,   9])

In [ ]:
arr_slice[:]=-100
arr_slice

array([-100, -100, -100])

In [ ]:
# **arr_copy **값이 변경되었지만 **arr** 값은 변경되지 않은 것을 확인할 수 있다.

arr

array([   0,    1,    2,    3,    4, -100, -100, -100,    8,    9])

## 차원 배열은 생각해야 할 것이 많아진다.
>2차원 배열을 생각해보자. 각 인덱스에 해당하는 원소는 스칼라가 아니고 1차원 벡터가 된다.

In [ ]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr2d
#arr2d[0]

array([1, 2, 3])

In [ ]:
# 개개의 원소들은 대괄호를 반복적으로 사용하여 접근할 수도 있고 쉼표를 이용하여 접근할 수도 있다.

arr2d[0][1][0]

2

In [ ]:
arr2d[0,1]

2

# 2차원 배열 인덱스에서 첫번째 성분은 행, 두번째 성분은 열을 의미한다고 볼 수 있다.

In [ ]:
# 다차원 배열에서 뒤쪽 인덱스를 생략하면 저차원 배열을 반환한다. 가령 2 x 2 x 3 배열
import numpy as np

arr3d = np.array([[[4, 5, 6],[1, 2, 3]],
                  [[7, 8, 9],[10, 11, 12]]
                 ])
arr3d

array([[[ 4,  5,  6],
        [ 1,  2,  3]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [ ]:
arr2=arr3d[0,1,:2]
arr2

array([1, 2])

In [ ]:
arr2[:]*=10
arr2

array([100, 200])

In [ ]:
arr3d

array([[[ 4,  5,  6],
        [ 1,  2,  3]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [ ]:
arr2=arr3d[0,1,:2]*10
arr2

In [ ]:

# arr3d[0]는 2 x 3 배열이 된다.
arr3d[0]

array([[  4,   5,   6],
       [100, 200,   3]])

In [ ]:
# arr3d[0, 1]은 1 x 3 배열

arr3d[0, 1]

array([4, 5, 6])

In [ ]:
# arr3d[0]에 스칼라 또는 벡터가 할당될 수 있다.
arr3d = np.array([[[1, 2, 3], [4, 5, 6]],
                  [[7, 8, 9], [10, 11, 12]]
                 ])
old = arr3d[0].copy()

#old[:]=100
old
#arr3d[0] = 100
#arr3d

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [ ]:
# 다음과 같이 인덱스 arr3d[0, 1]를 2단계로 나눠서 할 수 있다.

arr3d[0] = old

x = arr3d[0]
x

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
x[1]

array([4, 5, 6])

## 슬라이싱을 이용한 인덱싱

파이썬 리스트에 사용했던 슬라이싱을 넘파이 배열에서도 마찬가지로 사용할수 있다.

#### 2차원 배열 슬라이싱

![image.png]()

In [ ]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
arr2d[:2]

array([[1, 2, 3],
       [4, 5, 6]])


>위에서 보는 바와 같이 0번째, 1번째 1차원배열을 합친 2차원 배열을 반환하는 것을 알 수 있다. 인덱스를 성분별로 지정했듯이 슬라이싱도 성분별로 지정할 수 있다.

In [ ]:
arr2d[:2, 1:]

array([[2, 3],
       [5, 6]])

In [ ]:
arr2d[1, 1:]  #두번째행 두번째, 세번째열을 선택하려면 다음과 같이 할 수 있다

array([5, 6])

In [ ]:
arr2d[:2, 2]  #마찬가지로 3번째 열, 첫번째, 두번째 행을 선택은 다음과 같다

array([3, 6])

In [ ]:
arr2d[:, :1] #콜론은 모든 인덱스를 의미하므로 다음은 첫번째 열을 선택한다.

array([[1],
       [4],
       [7]])

In [ ]:
#앞에서와 마찬가지로 선택된 부분에 값을 대입하면 모든 값이 변경된다.
arr2d[:2, 1:] = 0
arr2d

array([[1, 0, 0],
       [4, 0, 0],
       [7, 8, 9]])

### 논리인덱싱

In [ ]:
# 중복된 이름 배열과 이름에 대응되는 숫자들 자료가 있다고 가정
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Bob', 'Joe'])

np.random.seed(0)

data = np.random.randn(7, 4)
data

array([[ 1.76405235,  0.40015721,  0.97873798,  2.2408932 ],
       [ 1.86755799, -0.97727788,  0.95008842, -0.15135721],
       [-0.10321885,  0.4105985 ,  0.14404357,  1.45427351],
       [ 0.76103773,  0.12167502,  0.44386323,  0.33367433],
       [ 1.49407907, -0.20515826,  0.3130677 , -0.85409574],
       [-2.55298982,  0.6536186 ,  0.8644362 , -0.74216502],
       [ 2.26975462, -1.45436567,  0.04575852, -0.18718385]])

In [ ]:
# Bob에 해당하는 숫자들의 행만 선택하기를 원한다. 비교 연산자 ==를 이용하면 벡터화된 논리 배열을 얻을 수 있다.
# 비교연산자(<,>,==,<=..)를 수행하면 결과는 항상 논리값이 나온다.
names =='Will'

array([False, False,  True, False,  True, False, False])

>이 논리배열은 다른 배열의 인덱스로 사용될 수 있다. 인덱스로 사용될 논리 배열의 크기와 인덱스를 사용할 배열의 크기가 같아야 한다.

In [ ]:
data[names == "Will"]

array([[-0.10321885,  0.4105985 ,  0.14404357,  1.45427351],
       [ 1.49407907, -0.20515826,  0.3130677 , -0.85409574]])

In [ ]:
# 다음과 같이 다중 인덱스를 사용할 수 있다

data[names == 'Bob', 2:]

array([[ 0.97873798,  2.2408932 ],
       [ 0.44386323,  0.33367433],
       [ 0.8644362 , -0.74216502]])

In [ ]:
#Bob을 제외한 모든 자료를 선택하려면 !=를 사용하면 된다.
data[names != 'Bob']

array([[ 1.86755799, -0.97727788,  0.95008842, -0.15135721],
       [-0.10321885,  0.4105985 ,  0.14404357,  1.45427351],
       [ 1.49407907, -0.20515826,  0.3130677 , -0.85409574],
       [ 2.26975462, -1.45436567,  0.04575852, -0.18718385]])

In [ ]:
#또는 부정 연산자 ~를 사용해도 된다
data[~(names == 'Bob')]

array([[ 1.86755799, -0.97727788,  0.95008842, -0.15135721],
       [-0.10321885,  0.4105985 ,  0.14404357,  1.45427351],
       [ 1.49407907, -0.20515826,  0.3130677 , -0.85409574],
       [ 2.26975462, -1.45436567,  0.04575852, -0.18718385]])

>여러 개의 조건을 결합하려면 &(and) 또는 |(or) 연산자를 사용하면 된다. 주의해야 할 것은 넘파이 논리 연산자로 파이썬 논리 연산자 and와 or를 사용할 수 없다. 반드시 &와 |만 사용해야 한다

In [ ]:
mask = (names == 'Bob') | (names == 'Will')
mask

array([ True, False,  True,  True,  True,  True, False])

In [ ]:
arr_m = data[mask]
arr_m

array([[ 1.76405235,  0.40015721,  0.97873798,  2.2408932 ],
       [-0.10321885,  0.4105985 ,  0.14404357,  1.45427351],
       [ 0.76103773,  0.12167502,  0.44386323,  0.33367433],
       [ 1.49407907, -0.20515826,  0.3130677 , -0.85409574],
       [-2.55298982,  0.6536186 ,  0.8644362 , -0.74216502]])

>또한 논리 인덱스를 이용해서 반환된 배열을 원래 배열의 복사본이기때문에 반환된 배열값이 바뀌어도 원본값은 변하지 않는다.

In [ ]:
arr_m[:, :2] = 0
arr_m

array([[ 0.        ,  0.        ,  0.97873798,  2.2408932 ],
       [ 0.        ,  0.        ,  0.14404357,  1.45427351],
       [ 0.        ,  0.        ,  0.44386323,  0.33367433],
       [ 0.        ,  0.        ,  0.3130677 , -0.85409574],
       [ 0.        ,  0.        ,  0.8644362 , -0.74216502]])

In [ ]:
data

array([[ 1.76405235,  0.40015721,  0.97873798,  2.2408932 ],
       [ 1.86755799, -0.97727788,  0.95008842, -0.15135721],
       [-0.10321885,  0.4105985 ,  0.14404357,  1.45427351],
       [ 0.76103773,  0.12167502,  0.44386323,  0.33367433],
       [ 1.49407907, -0.20515826,  0.3130677 , -0.85409574],
       [-2.55298982,  0.6536186 ,  0.8644362 , -0.74216502],
       [ 2.26975462, -1.45436567,  0.04575852, -0.18718385]])

>논리 배열 인덱스를 통해서 원래 배열의 값을 변경하는 것은 상식적이다.≈

In [ ]:
# 다음과 같이 인덱스 arr3d[0, 1]를 2단계로 나눠서 할 수 있다.

data[data < 0] = 0
data

array([[1.76405235, 0.40015721, 0.97873798, 2.2408932 ],
       [1.86755799, 0.        , 0.95008842, 0.        ],
       [0.        , 0.4105985 , 0.14404357, 1.45427351],
       [0.76103773, 0.12167502, 0.44386323, 0.33367433],
       [1.49407907, 0.        , 0.3130677 , 0.        ],
       [0.        , 0.6536186 , 0.8644362 , 0.        ],
       [2.26975462, 0.        , 0.04575852, 0.        ]])

In [ ]:
# 이름이 Joe가 아닌 행의 값을 7로 변경하는 것은 다음과 같다.
data[names != 'Joe'] = 7
data

array([[7.        , 7.        , 7.        , 7.        ],
       [1.86755799, 0.        , 0.95008842, 0.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [2.26975462, 0.        , 0.04575852, 0.        ]])

### 정수 배열을 이용한 인덱싱

In [ ]:
# 정수 배열을 이용해서 인덱싱을 자유롭게 할 수 있다. 예를 위해 다음과 같은 배열을 만들어 보자.
arr = np.empty((8, 4))

for i in range(8):
    arr[i] = i
arr

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [ ]:
# 원하는 행을 뽑아서 원하는 순서로 배열하고 싶으면 행에 해당하는 인덱스를 배열로 만들어 대입하면 된다.

arr[[4, 3, 0, 6]]

array([[4., 4., 4., 4.],
       [3., 3., 3., 3.],
       [0., 0., 0., 0.],
       [6., 6., 6., 6.]])

In [ ]:
# 음수 인덱스도 가능, 뒤에서 몇번째 인덱스, -4:뒤에서 4번째. 이때4번째를 포함

arr[[-4, -5, 0, 6]]

array([[4., 4., 4., 4.],
       [3., 3., 3., 3.],
       [0., 0., 0., 0.],
       [6., 6., 6., 6.]])

In [ ]:
# 여러 개의 정수 배열 인덱싱은 약간 다르다. 다중 정수 배열 인덱싱 결과는 항상 1차원 배열
arr = np.arange(32).reshape(8, 4)
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [ ]:
# 다음과 같이 정수열 배열 인덱스를 2개의 성분에 대입하면 결과값은 각각의 튜플에 해당하는 일차원 배열이 나온다.
arr[[1, 5, 7, 2], [0, 3, 1, 2]]

array([1., 5., 7., 2.])

>즉, 인덱스 (1, 0), (5, 3), (7, 1), (2, 2) 원소들이 일차원 배열로 반환된다.
>언뜻 보기에는 1, 5, 7, 2행 인덱스와 0, 3, 1, 2열 인덱스에 해당하는 직사각형 배열을 생각할 수 있지만 그렇지 않은 것을 알 수 있다. 이러한 배열은 다음과 같이 만들 수 있다.

In [ ]:
arr[[1, 5, 7, 2]][:, [0, 3, 1, 2]]

array([[1., 1., 1., 1.],
       [5., 5., 5., 5.],
       [7., 7., 7., 7.],
       [2., 2., 2., 2.]])

> 주의해야할 것은 정수 배열 인덱싱해서 나온 배열은 **원래 배열의 복사본**이다.

## 넘파이 배열 슬라이싱

>**[1:3]**처럼 1번과 2번 위치를 슬라이싱하거나, **[:3]**처럼 처음 ~ 2번 위치, **[1:]** 처럼 1번 위치부터 끝 부분을 슬라이싱하는 원리는 리스트와 동일<br/>
>각 axis마다 슬라이싱 결과가 반영되는데, 그림으로 이해하면 다음과 같다.
![image.png]()

In [ ]:
arr

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [ ]:
arr[2, 1:3]
arr[:2, 1:3]

array([[0., 0.],
       [1., 1.]])

In [ ]:
import numpy as np

A = np.array([[1,2,3,4], [5,6,7,8]])

#A[1, 1:3]
A[:1, 1:3] # 위와 같은 표현

array([[2, 3]])

In [ ]:
import numpy as np

a = np.array([[1, 2, 3, 4],
             [5, 6, 7, 8],
             [9, 10, 11, 12],
             [13, 14, 15, 16]])
a[::2, 1] # array([ 2, 10])

array([ 2, 10])

In [ ]:
a[::2, 1::2]

array([[ 2,  4],
       [10, 12]])

In [ ]:
a[::2, ...]

array([[ 1,  2,  3,  4],
       [ 9, 10, 11, 12]])

In [ ]:
a[::2, ::-1]

array([[ 4,  3,  2,  1],
       [12, 11, 10,  9]])

##4. numpy 연산

*   배열간 연산 가능
*   +,-,*,/ 등의 연산자 사용가능
*   add(),substract(),multiply(),divide()

In [ ]:
import numpy as np

a = np.array([1,2,3])
b = np.array([4,5,6])

# 각 요소 더하기
c = a+b

# c= np.add(a, b)
print(c) # [-3 -3 -3]

# 각 요소 곱하기
# c = a*b

[5 7 9]

In [ ]:
c = np.multiply(a, b)
print(c) #[4 10 18]

# 각 요소 나누기
# c = a/b

[ 4 10 18]

In [ ]:
c = np.divide(a,b)
print(c) # [0.25 0.4 0.5]

[0.25 0.4  0.5 ]

#### dot()함수: 행렬의 곱

In [ ]:
import numpy as np
arr1 = [[1,2],[3,4]]
arr2 = [[5,6],[7,8]]
a = np.array(arr1)
b = np.array(arr2)

c= np.dot(a, b)
print(c)

[[19 22]
 [43 50]]

#### 모든 원소의 합: sum(), 모든 원소의 곱 prod()

In [ ]:
import numpy as np

a = np.array([[-1,2,3],[3,4,8]])
s = np.sum(a)
print('sum=',a.sum())

# 행별/열별 연산 (axis=0/1)

sum= 19

In [ ]:
print('sum by row=',a.sum(axis=0))

sum by row= [ 2  6 11]

In [ ]:
print('mean=',a.mean())

mean= 3.1666666666666665

In [ ]:
print('sd=',a.std())

sd= 2.6718699236469

##5. 행렬연산
#### 덧셈과 뺄셈에서는 기본적으로 두 행렬의 행과 열의 크기가 같아야 한다. 예를 들어 행렬 A와B의 덧셈과 뺄셈은 다음과 같다.

\begin{align}
& A = \begin{bmatrix} 1 & 2 & 3 \\ 4 & 5 & 6 \end{bmatrix}, \ \ \   
  B = \begin{bmatrix} 7 & 8 & 9 \\ 10 & 11 & 12 \end{bmatrix} \\ \\
  & C=A+B = \begin{bmatrix} 8 & 10 & 12 \\ 14 & 16 & 18 \end{bmatrix} \\ \\
  & D=A-B = \begin{bmatrix} -6 & -6 & -6 \\ -6 & -6 & -6 \end{bmatrix}
\end{align}

In [ ]:
import numpy as np

A = np.array([[1,2,3], [4,5,6]])
B = np.array([1,2])

C = A+B
D = A-B

print("C=", C, "\nD=", D)

C= [[ 8 10 12]
 [11 13 15]]
D= [[-6 -6 -6]
 [-3 -3 -3]]

####그러면 A+3은? 행렬과 스칼라값과의 덧셈이다. <br/>행렬의 모든 성분에 3을 더하라는 얘기다. 뺄셈도 마찬가지다.

$$A+3=\begin{bmatrix} 4 & 5 & 6 \\ 7 & 8 & 9 \end{bmatrix}$$

In [ ]:
print("A+3=", A+3)

A+3= [[4 5 6]
 [7 8 9]]

>그렇다면, 다음 덧셈은 가능할까?\
$$A = \begin{bmatrix} 1 & 2 & 3 \\ 4 & 5 & 6 \end {bmatrix}, \
E=\begin{bmatrix} 1 \\ 2 \end{bmatrix}$$

>일 때, A+E는? \\
두 행렬의 행과 열의 길이가 다르므로 오류가 나야 맞지만 넘파이에서는 다음과 같이 행렬 E를 행렬 A의 열의 길이에 맞춰 늘려서 계산한다.

![image.png]()

In [ ]:
E = np.array([[1],[2]])
print("A+E=", A+E)

A+E= [[2 3 4]
 [6 7 8]]

>이와 같이 부족한 행과 열을 같은 성분으로 채워서 계산하는 방법을 브로드캐스팅(broadcasting)이라고 한다. 매트랩에서도 동일한 방법을 사용한다.

>매트랩에서는 행렬의 곱셈이 기본적으로 행렬 단위로 계산되는 것에 비해, 넘파이에서는 행렬의 성분 단위로 계산된다.

\begin{align}
& A = \begin{bmatrix} 1 & 2 & 3 \\ 4 & 5 & 6 \end{bmatrix}, \ \ \   
  B = \begin{bmatrix} 7 & 8 & 9 \\ 10 & 11 & 12 \end{bmatrix} \\ \\
  & A \star B = \begin{bmatrix} 7 & 16 & 27 \\ 40 & 55 & 72 \end{bmatrix}
\end{align}

In [ ]:
print("A*B=", A*B)

A*B= [[ 7 16 27]
 [40 55 72]]

>행렬의 성분 단위 곱셈에도 브로드캐스팅이 적용된다.

>행렬 곱셈을 하려면 행렬 A의 열과 행렬 B의 행의 길이가 같아야 한다. 넘파이에서 행렬 곱셈은 ndarray.dot 을 사용한다.

$$AB^T = \begin{bmatrix} 50 & 68  \\ 122 & 167 \end{bmatrix}$$

In [ ]:
G = A.dot(B.T)
print("AB^T=", G)

AB^T= [[ 50  68]
 [122 167]]

In [ ]:
# 행렬의 모든 성분의 총합은 ndarray.sum() 을 사용
print("A=", A, "\nA.sum=", A.sum())

A= [[1 2 3]
 [4 5 6]]
A.sum= 21

>행렬의 행 단위의 합은 ndarray.sum(axis=0), 열 단위의 합은 ndarray.sum(axis=1)을 사용한다.<br/> 행렬 A의 행 단위의 합은 [5 7 9]가, 열 단위의 합은 [6 15]인 1차원 어레이가 출력됨.


![image.png]()

In [ ]:
print(A.sum(axis=0), A.sum(axis=1))
print(A.sum(axis=0).shape, A.sum(axis=1).shape)

[5 7 9] [ 6 15]
(3,) (2,)

>행렬의 모든 성분의 평균은 ndarray.mean() 을 사용한다. <br/>
>행렬의 행 단위의 평균은 ndarray.mean(axis=0), 열 단위의 평균은 ndarray.mean(axis=1) 을 사용한다.

In [ ]:
print(A.mean(), A.mean(axis=0), A.mean(axis=1))

3.5 [2.5 3.5 4.5] [2. 5.]

>행렬의 모든 성분의 최대값은 ndarray.max() 을 사용한다. <br/>
>행렬의 행 단위의 최대값은 ndarray.max(axis=0), 열 단위의 최대값은 ndarray.max(axis=1) 을 사용

In [ ]:
print(A.max(), A.max(axis=0), A.max(axis=1))

6 [4 5 6] [3 6]

>최소값은 max 대신에 min 을 사용

In [ ]:
# 전치(transpose)는 크기변경(reshape)의 특별한 형태이다. 배열은 transpose 메소드를 가지며 T 속성도 가지고 있다.

import numpy as np

arr = np.arange(15).reshape((3, 5))
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [ ]:
# 배열의 T 속성을 이용하면 transpose를 할 수 있다.
arr.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [ ]:
# 행렬 계산을 할 때 전치 행렬을 자주 사용하게 된다. 예를 들어 두 행렬의 곱을 계산할 때 dot 메소드를 이용하는데 다음과 같이 계산할 수 있다.
arr.dot(arr.T)

array([[ 30,  80, 130],
       [ 80, 255, 430],
       [130, 430, 730]])

In [ ]:
# 고차원 배열에서 transpose는 축 인덱스를 인자로 갖는다. 다음과 같이 2 x 3 x 4 3차원 배열 arr3d를 생각해보자.
arr3d = np.arange(2 * 3 * 4).reshape((2, 3, 4))
arr3d

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [ ]:
# 다음은 두번째 축을 첫번째로, 첫번째 축은 두번째로 옮긴 예이다.

arr3d.transpose((1, 0 , 2))

array([[[ 0,  1,  2,  3],
        [12, 13, 14, 15]],

       [[ 4,  5,  6,  7],
        [16, 17, 18, 19]],

       [[ 8,  9, 10, 11],
        [20, 21, 22, 23]]])

> 위에서 두번째 축 성분을 고정시킨뒤 첫번째 축을 고정시키고 마지막 세번째 축 성분을 모두 나열하여 새로운 배열의 (0, 0) 성분 [0, 1, 2 3]을 만들고, 다음은 두번째 축은 고정시킨채 첫번째 축 성분을 이동하고 다음은 세번째 축 성분을 모두 나열하여 (0, 1) 성분 [12, 13, 14, 15]을 만든다. 두번째 성분을 하나 이동하여 [4, 5, 6, 7] 성분 (1, 0)을 찾고, 다음은 두번째 성분은 고정시킨채 첫번째 성분을 이동하여 [16, 17, 18, 19] 성분 (1, 1)을 만든다. 마지막으로 두번째 성분을 한번 더 이동하여 [8, 9, 10, 11] 성분 (2, 0)을 만들고, 첫번째 성분을 이동시켜 [20, 21, 22, 23] 성분 (2, 1)을 만든다. 최종적으로 3 x 2 x 4 배열이 만들어 진다.

>고차원 배열에서 T와 인자없는 transpose() 메소드는 원래 배열의 축의 순서를 거꾸로 출력한다

In [ ]:
# 의 arr3d 배열에 대해서 arr3d.transpose(2, 0, 1)의 값을 손으로 구하고 메소드로 구한 것과 비교
arr3d.T

array([[[ 0, 12],
        [ 4, 16],
        [ 8, 20]],

       [[ 1, 13],
        [ 5, 17],
        [ 9, 21]],

       [[ 2, 14],
        [ 6, 18],
        [10, 22]],

       [[ 3, 15],
        [ 7, 19],
        [11, 23]]])

In [ ]:
# swapaxes(i, j)는 i 축과 j축만 바꾸는 것이다. 따라서 arr3d.swapaxes(0, 2)는 arr3d.transpose(2, 1, 0)과 같다.

arr3d.swapaxes(2, 0)

array([[[ 0, 12],
        [ 4, 16],
        [ 8, 20]],

       [[ 1, 13],
        [ 5, 17],
        [ 9, 21]],

       [[ 2, 14],
        [ 6, 18],
        [10, 22]],

       [[ 3, 15],
        [ 7, 19],
        [11, 23]]])

#6. 범용함수
>넘파이 배열의 성분끼리 연산을 할 수 있는 함수

In [ ]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [ ]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

> 위와 같이 인자를 하나만 갖는 함수를 단항 함수(unary function)이라고 한다. <br/>add, maximum 함수들은 두 개의 인자를 갖는다.

In [ ]:
np.add(arr, arr)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [ ]:
rng = np.random.RandomState(0)

x = rng.randn(10)
y = rng.randn(10)
x

array([ 1.76405235,  0.40015721,  0.97873798,  2.2408932 ,  1.86755799,
       -0.97727788,  0.95008842, -0.15135721, -0.10321885,  0.4105985 ])

In [ ]:
y

array([ 0.14404357,  1.45427351,  0.76103773,  0.12167502,  0.44386323,
        0.33367433,  1.49407907, -0.20515826,  0.3130677 , -0.85409574])

In [ ]:
# maximum 함수는 두 배열의 같은 위치의 성분중 큰 값을 반환
np.maximum(x, y)

array([ 1.76405235,  1.45427351,  0.97873798,  2.2408932 ,  1.86755799,
        0.33367433,  1.49407907, -0.15135721,  0.3130677 ,  0.4105985 ])

In [ ]:
arr = rng.randn(7) * 5
arr

array([-12.76494908,   3.26809298,   4.32218099,  -3.7108251 ,
        11.34877312,  -7.27182837,   0.22879259])

>흔하지는 않지만 범용함수 중 여러 개의 값을 반환하는 것도 있다. <br/>
파이썬 내장함수 divmod와 같은 역할을 하는 modf라는 함수는 정수와 소수부분을 각각 반환한다.

In [ ]:
rem_part, int_part = np.modf(arr)
rem_part

array([-0.76494908,  0.26809298,  0.32218099, -0.7108251 ,  0.34877312,
       -0.27182837,  0.22879259])

In [ ]:
int_part

array([-12.,   3.,   4.,  -3.,  11.,  -7.,   0.])

In [ ]:
# 범용함수는 선택 인자 out=을 이용해서 결과값이 저장되는 공간을 자신으로 지정할 수 있다.
np.sqrt(arr, out=arr)

<ipython-input-151-fb580f289e8a>:2: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(arr, out=arr)

array([       nan, 1.80778676, 2.07898557,        nan, 3.36879402,
              nan, 0.47832268])

In [ ]:
arr

array([       nan, 1.80778676, 2.07898557,        nan, 3.36879402,
              nan, 0.47832268])

#7.array를 list로 바꾸기
>파이썬의 리스트 자료형을 넘파이 배열로 바꾸거나<br/>
numpy array에서 list 자료형으로 바꾸는 방법

##(1) list를 numpy array로 바꾸기 : np.array 함수
>리스트를 넘파이 어레이로 만드는 방법은 **np.array** 함수를 이용.<br/>
>단, 다차원 array에서는 **내부 배열 간 원소 개수가 같아야 하기**에,해당 조건이 위배되는 경우에는 내부 원소는 list 형태로 잔류하게 됨.

In [ ]:
import numpy as np

a = [1.5, 3.7, 4.4, 9.2]
b = [[1, 3, 5], [2, 4, 6]]
c = [[1], [2, 3], [4, 5, 6]]
print(a)
np.array(a) # array([1.5, 3.7, 4.4, 9.2])

[1.5, 3.7, 4.4, 9.2]

array([1.5, 3.7, 4.4, 9.2])

In [ ]:
np.array(b)

array([[1, 3, 5],
       [2, 4, 6]])

In [ ]:
np.array(c)
#np.array([list([1]), list([2, 3]), list([4, 5, 6])], dtype=object)

array([list([1]), list([2, 3]), list([4, 5, 6])], dtype=object)

>b는 내부 리스트 내 원소가 3, 3개로 개수가 같아 2차원 array로 정상 변환되었지만, c는 내부 리스트 원소 개수가 1, 2, 3개로 일치하지 않아
2차원 array로 정상 변환되지 못하고 내부 원소들이 list 형태로 남아있음(valueError)

##(2) numpy array를 list로 바꾸기 : tolist 함수<br/>
>numpy array를 반대로 list로 바꾸는 방법도 tolist 함수로 쉽게 수행이 가능.<br/>
>list 메소드도 사용이 가능하긴 하지만,다차원 배열에서는 내부 배열이 array 형태로 잔류한다는 점에서 차이가 있음

In [ ]:
a = np.array([1.2, 3.4, 5.6, 7.8])
b = np.array([[1, 3], [5, 7]])

list(a) # [1.2, 3.4, 5.6, 7.8]

[1.2, 3.4, 5.6, 7.8]

In [ ]:
a.tolist() # [1.2, 3.4, 5.6, 7.8]

[1.2, 3.4, 5.6, 7.8]

In [ ]:
list(b) # [array([1, 3]), array([5, 7])]

[array([1, 3]), array([5, 7])]

In [ ]:
b.tolist() # [[1, 3], [5, 7]]

[[1, 3], [5, 7]]

>1차원 배열인 a는 list 메소드로도 리스트 정상 변환이 가능했지만, 2차원 배열인 b는 tolist 메소드를 이용해야 다차원 리스트로 변환이 가능

#pandas
##시리즈 생성
  - 리스트 -> 시리즈

In [ ]:
pip install pandas

Requirement already satisfied: pandas in /usr/local/lib/python3.10/dist-packages (2.2.2)
Requirement already satisfied: numpy>=1.22.4 in /usr/local/lib/python3.10/dist-packages (from pandas) (1.26.4)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.10/dist-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas) (2024.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.10/dist-packages (from pandas) (2024.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.10/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [ ]:
import pandas as pd

a = pd.Series([1, 2, 3, 4])
print(a)
b = pd.Series([1, 2, 3], index=['a', 'b', 'c'])
print(b)

0    1
1    2
2    3
3    4
dtype: int64
a    1
b    2
c    3
dtype: int64

##데이터프레임 생성
- 리스트 -> 데이터프레임 생성

In [ ]:
list1 = list([['한빛', '남자', '20', '180'],
              ['한결', '남자', '21', '177'],
              ['한라', '여자', '20', '160']])

col_names = ['이름', '성별', '나이', '키']

pd.DataFrame(list1, columns=col_names)

   이름  성별  나이    키
0  한빛  남자  20  180
1  한결  남자  21  177
2  한라  여자  20  160

- 딕셔너리 -> 데이터프레임
    - 딕셔너리의 키 -> 열 이름 / 값 -> 열에 대한 각 행의 데이터

In [ ]:
dict1 = {'이름':{0:'한빛', 1:'한결', 2:'한라'},
         '성별':{0:'남자', 1:'남자', 2:'여자'},
         '나이':{0:'20', 1:'21', 2:'20'},
         '키':{0:'180', 1:'177', 2:'160'}}
pd.DataFrame(dict1)

   이름  성별  나이    키
0  한빛  남자  20  180
1  한결  남자  21  177
2  한라  여자  20  160

- 넘파이의 다차원 배열 -> 데이터프레임

In [ ]:
import numpy as np

#배열
arr1=np.array([['한빛','남자','20','180'],
              ['한결','남자','21','177'],
              ['한라','여자','20','160']])

#열 이름 리스트
col_names=['이름','성별','나이','키']

#데이터프레임 생성하기
pd.DataFrame(arr1, columns=col_names)

   이름  성별  나이    키
0  한빛  남자  20  180
1  한결  남자  21  177
2  한라  여자  20  160

- CSV 파일 -> 데이터프레임

In [ ]:
list1 = list([['허준호','남자','30','183'],
 	['이가원','여자','24','162'],
 	['배규민','남자','23','179'],
 	['고고림','남자','21','182'],
 	['이새봄','여자','28','160'],
 	['이보람','여자','26','163'],
 	['이루리','여자','24','157'],
 	['오다현','여자','24','172']])
col_names = ['이름','성별','나이','키']
df = pd.DataFrame(list1, columns=col_names)
df

    이름  성별  나이    키
0  허준호  남자  30  183
1  이가원  여자  24  162
2  배규민  남자  23  179
3  고고림  남자  21  182
4  이새봄  여자  28  160
5  이보람  여자  26  163
6  이루리  여자  24  157
7  오다현  여자  24  172

- 데이터프레임 -> CSV 파일

In [ ]:
#디렉토리에 CSV 파일로 저장하기
df.to_csv('./file.csv', header=True, index=False, encoding='utf-8')

#CSV 파일 읽기
df2 = pd.read_csv('./file.csv', sep=',')

df2

    이름  성별  나이    키
0  허준호  남자  30  183
1  이가원  여자  24  162
2  배규민  남자  23  179
3  고고림  남자  21  182
4  이새봄  여자  28  160
5  이보람  여자  26  163
6  이루리  여자  24  157
7  오다현  여자  24  172

In [ ]:
#모든 열 이름 조회
df2.columns

Index(['이름', '성별', '나이', '키'], dtype='object')

## 데이터프레임 값 개수와 빈도수 확인
- count : 값의 개수
- unique : 유일한 값의 개수
- top : 제일 개수가 많은 값 (개수가 같은 값이 여러개 -> 먼저 나온 값이 top)
- freq : 빈도수, 즉 그 개수

In [ ]:
df.describe()

         이름  성별  나이    키
count     8   8   8    8
unique    8   2   6    8
top     허준호  여자  24  183
freq      1   5   3    1

In [ ]:
df.head(3)

    이름  성별  나이    키
0  허준호  남자  30  183
1  이가원  여자  24  162
2  배규민  남자  23  179

In [ ]:
df.tail(5)

    이름  성별  나이    키
3  고고림  남자  21  182
4  이새봄  여자  28  160
5  이보람  여자  26  163
6  이루리  여자  24  157
7  오다현  여자  24  172

In [ ]:
# 리스트를 사용하여 DataFrame 객체 생성하기
import pandas as pd

data = [['A', 1], ['B', 2], ['C', 3]]
df = pd.DataFrame(data, columns=['col1', 'col2'])
print(df)

  col1  col2
0    A     1
1    B     2
2    C     3

In [ ]:
# 딕셔너리를 사용하여 DataFrame 객체 생성하기
data = {'col1': ['A', 'B', 'C'], 'col2': [1, 2, 3]}
df = pd.DataFrame(data)
print(df)

  col1  col2
0    A     1
1    B     2
2    C     3

## 열 선택하기

In [ ]:
# CSV 파일을 사용하여 DataFrame 객체 생성하기
df = pd.read_csv('file.csv')
print(df)

    이름  성별  나이    키
0  허준호  남자  30  183
1  이가원  여자  24  162
2  배규민  남자  23  179
3  고고림  남자  21  182
4  이새봄  여자  28  160
5  이보람  여자  26  163
6  이루리  여자  24  157
7  오다현  여자  24  172

In [ ]:
df['이름']

0    허준호
1    이가원
2    배규민
3    고고림
4    이새봄
5    이보람
6    이루리
7    오다현
Name: 이름, dtype: object

In [ ]:
df[['이름','나이']]

    이름  나이
0  허준호  30
1  이가원  24
2  배규민  23
3  고고림  21
4  이새봄  28
5  이보람  26
6  이루리  24
7  오다현  24

## 행 선택하기

In [ ]:
df.loc[0]

이름    허준호
성별     남자
나이     30
키     183
Name: 0, dtype: object

In [ ]:
df.loc[[1,2]]

    이름  성별  나이    키
1  이가원  여자  24  162
2  배규민  남자  23  179

## 데이터 추가, 삭제, 수정

In [ ]:
#열 추가

df['등수']=[1,3,2,5,4,7,8,6]

In [ ]:
df

    이름  성별  나이    키  등수
0  허준호  남자  30  183   1
1  이가원  여자  24  162   3
2  배규민  남자  23  179   2
3  고고림  남자  21  182   5
4  이새봄  여자  28  160   4
5  이보람  여자  26  163   7
6  이루리  여자  24  157   8
7  오다현  여자  24  172   6

In [ ]:
#열 삭제

df.drop('등수',axis=1, inplace=True)

In [ ]:
df

    이름  성별  나이    키
0  허준호  남자  30  183
1  이가원  여자  24  162
2  배규민  남자  23  179
3  고고림  남자  21  182
4  이새봄  여자  28  160
5  이보람  여자  26  163
6  이루리  여자  24  157
7  오다현  여자  24  172

In [ ]:
#행 추가하기
df.loc[8] = ['홍길동','남자',25,176]

In [ ]:
df

    이름  성별  나이    키
0  허준호  남자  30  183
1  이가원  여자  24  162
2  배규민  남자  23  179
3  고고림  남자  21  182
4  이새봄  여자  28  160
5  이보람  여자  26  163
6  이루리  여자  24  157
7  오다현  여자  24  172
8  홍길동  남자  25  176

In [ ]:
#행 삭제
df.drop(8, inplace=True)

In [ ]:
df# 열 이름 변경하기

    이름  성별  나이    키
0  허준호  남자  30  183
1  이가원  여자  24  162
2  배규민  남자  23  179
3  고고림  남자  21  182
4  이새봄  여자  28  160
5  이보람  여자  26  163
6  이루리  여자  24  157
7  오다현  여자  24  172

In [ ]:
# 열 이름 변경하기

df.rename(columns={'이름':'name'}, inplace=True)

In [ ]:
df

  name  성별  나이    키
0  허준호  남자  30  183
1  이가원  여자  24  162
2  배규민  남자  23  179
3  고고림  남자  21  182
4  이새봄  여자  28  160
5  이보람  여자  26  163
6  이루리  여자  24  157
7  오다현  여자  24  172

#판다스 데이터 불러오기
- csv
- excel

In [3]:
import pandas as pd

In [ ]:
#csv 파일 불러오기
df=pd.read_csv('data.csv')

In [ ]:
# Excel 파일 불러오기
df = pd.read_excel('data.xlsx')

In [4]:
# 데이터 불러오기
url = "https://raw.githubusercontent.com/Datamanim/pandas/main/Jeju.csv"
df = pd.read_csv(url, encoding="EUC-KR")

print(df)

         id          일자   시도명  읍면동명         거주인구       근무인구        방문인구  \
0     22448  2018-01-01   제주시   도두동    32249.987   3418.266  102709.092
1     22449  2018-01-01   제주시   외도동   213500.997  10341.172  112692.789
2     22450  2018-01-01   제주시  이도2동  1212382.218  96920.834  541194.481
3     22451  2018-01-01   제주시  일도1동    33991.653   6034.253   72155.919
4     22452  2018-01-01  서귀포시   대천동   155036.925   9403.969  150882.409
...     ...         ...   ...   ...          ...        ...         ...
9616  32064  2020-04-30  서귀포시   표선면   228260.005  16891.732  152832.449
9617  32065  2020-04-30   제주시   한림읍   459959.064  26007.122  249700.419
9618  32066  2020-04-30   제주시   도두동    28397.481   3144.895   84052.697
9619  32067  2020-04-30  서귀포시   안덕면   348037.846  29106.286  251129.660
9620  32068  2020-04-30   제주시    연동  1010643.372  65673.477  447622.068

           총 유동인구   평균 속도  평균 소요 시간  평균 기온  일강수량  평균 풍속
0      138377.345  39.556    29.167    5.0   0.0   2.50
1      336534.958  32.900    30.900    5.0   0.0   2.50
2     1850497.533  29.538    35.692    2.9   0.0   2.40
3      112181.825  30.000    23.500    2.9   0.0   2.40
4      315323.303  41.583    14.375    5.1   0.0   2.30
...           ...     ...       ...    ...   ...    ...
9616   397984.186  44.514    34.054   18.1   0.0   4.70
9617   735666.605  48.609    61.377   18.0   0.0   4.35
9618   115595.073  41.053    29.421   20.3   0.0   3.00
9619   628273.792  46.595    49.189   17.6   0.0   3.50
9620  1523938.917  40.863    27.765   14.1   0.0   4.80

[9621 rows x 13 columns]

In [ ]:

print(df.tail(3))

         id          일자   시도명 읍면동명         거주인구       근무인구        방문인구  \
9618  32066  2020-04-30   제주시  도두동    28397.481   3144.895   84052.697
9619  32067  2020-04-30  서귀포시  안덕면   348037.846  29106.286  251129.660
9620  32068  2020-04-30   제주시   연동  1010643.372  65673.477  447622.068

           총 유동인구   평균 속도  평균 소요 시간  평균 기온  일강수량  평균 풍속
9618   115595.073  41.053    29.421   20.3   0.0    3.0
9619   628273.792  46.595    49.189   17.6   0.0    3.5
9620  1523938.917  40.863    27.765   14.1   0.0    4.8

In [ ]:
ans = df.select_dtypes(exclude=object).columns
print(ans)

Index(['id', '거주인구', '근무인구', '방문인구', '총 유동인구', '평균 속도', '평균 소요 시간', '평균 기온',
       '일강수량', '평균 풍속'],
      dtype='object')

In [ ]:
ans = df.select_dtypes(include=object).columns
print(ans)

Index(['일자', '시도명', '읍면동명'], dtype='object')

In [ ]:
print(df.isnull().sum())

id          0
일자          0
시도명         0
읍면동명        0
거주인구        0
근무인구        0
방문인구        0
총 유동인구      0
평균 속도       0
평균 소요 시간    0
평균 기온       0
일강수량        0
평균 풍속       0
dtype: int64

In [ ]:
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9621 entries, 0 to 9620
Data columns (total 13 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   id        9621 non-null   int64
 1   일자        9621 non-null   object
 2   시도명       9621 non-null   object
 3   읍면동명      9621 non-null   object
 4   거주인구      9621 non-null   float64
 5   근무인구      9621 non-null   float64
 6   방문인구      9621 non-null   float64
 7   총 유동인구    9621 non-null   float64
 8   평균 속도     9621 non-null   float64
 9   평균 소요 시간  9621 non-null   float64
 10  평균 기온     9621 non-null   float64
 11  일강수량      9621 non-null   float64
 12  평균 풍속     9621 non-null   float64
dtypes: float64(9), int64(1), object(3)
memory usage: 977.3+ KB
None

In [ ]:
print(df.describe())

                 id          거주인구           근무인구           방문인구        총 유동인구  \
count   9621.000000  9.621000e+03    9621.000000    9621.000000  9.621000e+03
mean   27258.000000  3.174315e+05   35471.201510  195889.561802  5.487922e+05
std     2777.487804  2.982079e+05   40381.214775  140706.090325  4.608802e+05
min    22448.000000  9.305552e+03    1407.936000   11538.322000  2.225181e+04
25%    24853.000000  9.539939e+04   12074.498000   99632.153000  2.216910e+05
50%    27258.000000  2.221105e+05   21960.928000  152805.335000  3.866935e+05
75%    29663.000000  4.106671e+05   40192.032000  236325.109000  6.406918e+05
max    32068.000000  1.364504e+06  263476.965000  723459.209000  2.066484e+06

             평균 속도     평균 소요 시간        평균 기온         일강수량        평균 풍속
count  9621.000000  9621.000000  9621.000000  9621.000000  9621.000000
mean     41.109084    37.215873    13.550828     6.972426     2.753171
std       8.758631    12.993786     7.745515    27.617260     1.498538
min      24.333000    12.667000    -9.600000     0.000000     0.000000
25%      34.250000    27.889000     7.600000     0.000000     1.700000
50%      39.640000    34.500000    13.400000     0.000000     2.400000
75%      49.105000    46.176000    19.700000     1.500000     3.400000
max     103.000000   172.200000    30.400000   587.500000    13.333000

In [ ]:
print(df['거주인구'])

0         32249.987
1        213500.997
2       1212382.218
3         33991.653
4        155036.925
           ...
9616     228260.005
9617     459959.064
9618      28397.481
9619     348037.846
9620    1010643.372
Name: 거주인구, Length: 9621, dtype: float64

In [ ]:
v_data = df['평균 속도']
q3 = v_data.quantile(0.75)
q1 = v_data.quantile(0.25)

iqr = q3 - q1
print(iqr)

14.854999999999997

In [ ]:
print(df['읍면동명'].nunique())

41

In [ ]:
print(df["읍면동명"].unique())

['도두동' '외도동' '이도2동' '일도1동' '대천동' '서홍동' '한경면' '송산동' '조천읍' '일도2동' '영천동'
 '예래동' '대륜동' '삼도1동' '이호동' '건입동' '중앙동' '삼양동' '삼도2동' '이도1동' '남원읍' '대정읍'
 '정방동' '효돈동' '아라동' '한림읍' '구좌읍' '용담1동' '오라동' '화북동' '연동' '표선면' '중문동' '성산읍'
 '안덕면' '천지동' '노형동' '동홍동' '용담2동' '봉개동' '애월읍']

## dataframe에서 중복 제거하고 첫번째/마지막 케이스 남기기(drop_duplicates 이용)

In [ ]:
# 데이터 불러오기
DataUrl = 'https://raw.githubusercontent.com/Datamanim/pandas/main/chipo.csv'
df = pd.read_csv(DataUrl)

In [ ]:
print(df)

      order_id  quantity                              item_name  \
0            1         1           Chips and Fresh Tomato Salsa
1            1         1                                   Izze
2            1         1                       Nantucket Nectar
3            1         1  Chips and Tomatillo-Green Chili Salsa
4            2         2                           Chicken Bowl
...        ...       ...                                    ...
4617      1833         1                          Steak Burrito
4618      1833         1                          Steak Burrito
4619      1834         1                     Chicken Salad Bowl
4620      1834         1                     Chicken Salad Bowl
4621      1834         1                     Chicken Salad Bowl

                                     choice_description item_price
0                                                   NaN     $2.39
1                                          [Clementine]     $3.39
2                                               [Apple]     $3.39
3                                                   NaN     $2.39
4     [Tomatillo-Red Chili Salsa (Hot), [Black Beans...    $16.98
...                                                 ...        ...
4617  [Fresh Tomato Salsa, [Rice, Black Beans, Sour ...    $11.75
4618  [Fresh Tomato Salsa, [Rice, Sour Cream, Cheese...    $11.75
4619  [Fresh Tomato Salsa, [Fajita Vegetables, Pinto...    $11.25
4620  [Fresh Tomato Salsa, [Fajita Vegetables, Lettu...     $8.75
4621  [Fresh Tomato Salsa, [Fajita Vegetables, Pinto...     $8.75

[4622 rows x 5 columns]

In [ ]:
# df의 item_name 컬럼 값이 Steak Salad 또는 Bowl 인 데이터를 데이터 프레임화 한 후, item_name를 기준으로 중복행이 있으면 제거하되 첫번째 케이스만 남겨라
df[df['item_name'].isin(['Steak Salad','Bowl'])]['item_name'].drop_duplicates(keep='first')

445           Bowl
664    Steak Salad
Name: item_name, dtype: object

#**dataframe에서 특정 문자열을 갖는 데이터만 인덱싱하기**

In [ ]:
df

,order_id,quantity,item_name,choice_description,item_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,$2.39
1,1,1,Izze,[Clementine],$3.39
2,1,1,Nantucket Nectar,[Apple],$3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,$2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",$16.98
...,...,...,...,...,...
4617,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Sour ...",$11.75
4618,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Sour Cream, Cheese...",$11.75
4619,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$11.25
4620,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Lettu...",$8.75
4621,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$8.75

In [ ]:
# df의 데이터 중 choice_description 값에 Black이 들어가는 경우를 인덱싱하라
df[df['choice_description'].str.contains('Black',na=False)]

,order_id,quantity,item_name,choice_description,item_price
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",$16.98
7,4,1,Steak Burrito,"[Tomatillo Red Chili Salsa, [Fajita Vegetables...",$11.75
9,5,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Pinto...",$9.25
11,6,1,Chicken Crispy Tacos,"[Roasted Chili Corn Salsa, [Fajita Vegetables,...",$8.75
12,6,1,Chicken Soft Tacos,"[Roasted Chili Corn Salsa, [Rice, Black Beans,...",$8.75
...,...,...,...,...,...
4604,1828,1,Chicken Bowl,"[Fresh Tomato Salsa, [Rice, Black Beans, Chees...",$8.75
4608,1829,1,Veggie Burrito,"[Tomatillo Red Chili Salsa, [Fajita Vegetables...",$11.25
4611,1830,1,Veggie Burrito,"[Tomatillo Green Chili Salsa, [Rice, Fajita Ve...",$11.25
4612,1831,1,Carnitas Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Rice,...",$9.25
4617,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Sour ...",$11.75

In [ ]:
# df의 데이터 중 choice_description 값에 Black이 들어가는 경우를 인덱싱하라
contains_black = lambda x: 'Black' in x if isinstance(x, str) else False
result = df[df['choice_description'].apply(contains_black)]
result

,order_id,quantity,item_name,choice_description,item_price
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",$16.98
7,4,1,Steak Burrito,"[Tomatillo Red Chili Salsa, [Fajita Vegetables...",$11.75
9,5,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Pinto...",$9.25
11,6,1,Chicken Crispy Tacos,"[Roasted Chili Corn Salsa, [Fajita Vegetables,...",$8.75
12,6,1,Chicken Soft Tacos,"[Roasted Chili Corn Salsa, [Rice, Black Beans,...",$8.75
...,...,...,...,...,...
4604,1828,1,Chicken Bowl,"[Fresh Tomato Salsa, [Rice, Black Beans, Chees...",$8.75
4608,1829,1,Veggie Burrito,"[Tomatillo Red Chili Salsa, [Fajita Vegetables...",$11.25
4611,1830,1,Veggie Burrito,"[Tomatillo Green Chili Salsa, [Rice, Fajita Ve...",$11.25
4612,1831,1,Carnitas Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Rice,...",$9.25
4617,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Sour ...",$11.75

## **dataframe에서 특정 컬럼 선택하기(DF.iloc이용)**

In [ ]:
df

,order_id,quantity,item_name,choice_description,item_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,$2.39
1,1,1,Izze,[Clementine],$3.39
2,1,1,Nantucket Nectar,[Apple],$3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,$2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",$16.98
...,...,...,...,...,...
4617,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Sour ...",$11.75
4618,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Sour Cream, Cheese...",$11.75
4619,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$11.25
4620,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Lettu...",$8.75
4621,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$8.75

In [ ]:
#df의 짝수번째 컬럼만을 포함하는 데이터프레임을 출력하라
df.iloc[:,range(0,len(df.columns),2)]

      order_id                              item_name item_price
0            1           Chips and Fresh Tomato Salsa     $2.39
1            1                                   Izze     $3.39
2            1                       Nantucket Nectar     $3.39
3            1  Chips and Tomatillo-Green Chili Salsa     $2.39
4            2                           Chicken Bowl    $16.98
...        ...                                    ...        ...
4617      1833                          Steak Burrito    $11.75
4618      1833                          Steak Burrito    $11.75
4619      1834                     Chicken Salad Bowl    $11.25
4620      1834                     Chicken Salad Bowl     $8.75
4621      1834                     Chicken Salad Bowl     $8.75

[4622 rows x 3 columns]

In [ ]:
#df의 두 번째 컬럼부터 2씩 건너뛰며 컬럼을 선택하는 코드
df.iloc[:,1::2]

      quantity                                 choice_description
0            1                                                NaN
1            1                                       [Clementine]
2            1                                            [Apple]
3            1                                                NaN
4            2  [Tomatillo-Red Chili Salsa (Hot), [Black Beans...
...        ...                                                ...
4617         1  [Fresh Tomato Salsa, [Rice, Black Beans, Sour ...
4618         1  [Fresh Tomato Salsa, [Rice, Sour Cream, Cheese...
4619         1  [Fresh Tomato Salsa, [Fajita Vegetables, Pinto...
4620         1  [Fresh Tomato Salsa, [Fajita Vegetables, Lettu...
4621         1  [Fresh Tomato Salsa, [Fajita Vegetables, Pinto...

[4622 rows x 2 columns]

### "::2"과 유사한 코드
- df.iloc[:,1::2] # 두 번째 컬럼부터 2씩 건너뛰며 컬럼을 선택하는 코드
- df.iloc[:,::3]  # 세 번째 컬럼부터 3씩 건너뛰며 컬럼을 선택하는 코드
- df.iloc[:,:10:2] # 0부터 9번째까지의 컬럼 중에서 2씩 건너뛰며 컬럼을 선택하는 코드

#dataframe에서  특정 단어로 시작하는 데이터 추출하기
**굵은 텍스트**

In [ ]:
#df의 데이터 중 item_name 값이 N으로 시작하는 데이터를 모두 추출하라.
df[df['item_name'].apply(lambda x : str(x)[0]=='N')]

,order_id,quantity,item_name,choice_description,item_price
2,1,1,Nantucket Nectar,[Apple],$3.39
22,11,1,Nantucket Nectar,[Pomegranate Cherry],$3.39
105,46,1,Nantucket Nectar,[Pineapple Orange Banana],$3.39
173,77,1,Nantucket Nectar,[Apple],$3.39
205,91,1,Nantucket Nectar,[Peach Orange],$3.39
436,189,1,Nantucket Nectar,[Pomegranate Cherry],$3.39
601,247,2,Nantucket Nectar,[Pineapple Orange Banana],$6.78
925,381,1,Nantucket Nectar,[Pomegranate Cherry],$3.39
1356,553,1,Nantucket Nectar,[Pomegranate Cherry],$3.39
1585,641,1,Nantucket Nectar,[Peach Orange],$3.39
1626,656,1,Nantucket Nectar,[Pineapple Orange Banana],$3.39
1706,690,1,Nantucket Nectar,[Apple],$3.39
2162,872,1,Nantucket Nectar,[Pineapple Orange Banana],$3.39
2379,947,2,Nantucket Nectar,[Peach Orange],$6.78
2381,947,1,Nantucket Nectar,[Apple],$3.39
2430,965,1,Nantucket Nectar,[Pomegranate Cherry],$3.39
2653,1053,1,Nantucket Nectar,[Pineapple Orange Banana],$3.39
2818,1118,1,Nantucket Nectar,[Apple],$3.39
2838,1128,1,Nantucket Nectar,[Peach Orange],$3.39
2853,1133,1,Nantucket Nectar,[Apple],$3.39
2949,1172,1,Nantucket Nectar,[Peach Orange],$3.39
3318,1330,1,Nantucket Nectar,[Peach Orange],$3.39
3368,1351,1,Nantucket Nectar,[Pineapple Orange Banana],$3.39
3570,1433,1,Nantucket Nectar,[Pineapple Orange Banana],$3.39
3845,1541,1,Nantucket Nectar,[Peach Orange],$3.39
4019,1609,1,Nantucket Nectar,[Pineapple Orange Banana],$3.39
4078,1632,1,Nantucket Nectar,[Peach Orange],$3.39

In [ ]:
#df의 데이터 중 item_name 값이 N으로 시작하는 데이터를 모두 추출하라.
df[df.item_name.str.startswith('N')]

,order_id,quantity,item_name,choice_description,item_price
2,1,1,Nantucket Nectar,[Apple],$3.39
22,11,1,Nantucket Nectar,[Pomegranate Cherry],$3.39
105,46,1,Nantucket Nectar,[Pineapple Orange Banana],$3.39
173,77,1,Nantucket Nectar,[Apple],$3.39
205,91,1,Nantucket Nectar,[Peach Orange],$3.39
436,189,1,Nantucket Nectar,[Pomegranate Cherry],$3.39
601,247,2,Nantucket Nectar,[Pineapple Orange Banana],$6.78
925,381,1,Nantucket Nectar,[Pomegranate Cherry],$3.39
1356,553,1,Nantucket Nectar,[Pomegranate Cherry],$3.39
1585,641,1,Nantucket Nectar,[Peach Orange],$3.39
1626,656,1,Nantucket Nectar,[Pineapple Orange Banana],$3.39
1706,690,1,Nantucket Nectar,[Apple],$3.39
2162,872,1,Nantucket Nectar,[Pineapple Orange Banana],$3.39
2379,947,2,Nantucket Nectar,[Peach Orange],$6.78
2381,947,1,Nantucket Nectar,[Apple],$3.39
2430,965,1,Nantucket Nectar,[Pomegranate Cherry],$3.39
2653,1053,1,Nantucket Nectar,[Pineapple Orange Banana],$3.39
2818,1118,1,Nantucket Nectar,[Apple],$3.39
2838,1128,1,Nantucket Nectar,[Peach Orange],$3.39
2853,1133,1,Nantucket Nectar,[Apple],$3.39
2949,1172,1,Nantucket Nectar,[Peach Orange],$3.39
3318,1330,1,Nantucket Nectar,[Peach Orange],$3.39
3368,1351,1,Nantucket Nectar,[Pineapple Orange Banana],$3.39
3570,1433,1,Nantucket Nectar,[Pineapple Orange Banana],$3.39
3845,1541,1,Nantucket Nectar,[Peach Orange],$3.39
4019,1609,1,Nantucket Nectar,[Pineapple Orange Banana],$3.39
4078,1632,1,Nantucket Nectar,[Peach Orange],$3.39

In [ ]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

df['choice_description_encoded'] = le.fit_transform(df['choice_description'])

df.groupby('item_name').choice_description_encoded.agg(['mean','min','max'])

                                              mean   min   max
item_name
6 Pack Soft Drink                        92.685185    14   583
Barbacoa Bowl                           543.015152    31  1042
Barbacoa Burrito                        599.395604    19  1031
Barbacoa Crispy Tacos                   561.272727   120  1000
Barbacoa Salad Bowl                     433.500000   120   703
Barbacoa Soft Tacos                     651.600000   126   905
Bottled Water                          1043.000000  1043  1043
Bowl                                      6.000000     3     9
Burrito                                 301.833333     0   898
Canned Soda                             157.432692    13   583
Canned Soft Drink                       174.405316    14   583
Carnitas Bowl                           484.500000    23  1036
Carnitas Burrito                        414.525424    29  1021
Carnitas Crispy Tacos                   482.571429    64   847
Carnitas Salad                          913.000000   913   913
Carnitas Salad Bowl                     461.000000   251   678
Carnitas Soft Tacos                     495.425000    54   858
Chicken Bowl                            457.844353    27  1039
Chicken Burrito                         470.160940    19  1040
Chicken Crispy Tacos                    396.808511    44   809
Chicken Salad                           234.000000    42  1023
Chicken Salad Bowl                      327.454545   119   775
Chicken Soft Tacos                      427.286957    51  1037
Chips                                  1043.000000  1043  1043
Chips and Fresh Tomato Salsa           1043.000000  1043  1043
Chips and Guacamole                    1043.000000  1043  1043
Chips and Mild Fresh Tomato Salsa      1043.000000  1043  1043
Chips and Roasted Chili Corn Salsa     1043.000000  1043  1043
Chips and Roasted Chili-Corn Salsa     1043.000000  1043  1043
Chips and Tomatillo Green Chili Salsa  1043.000000  1043  1043
Chips and Tomatillo Red Chili Salsa    1043.000000  1043  1043
Chips and Tomatillo-Green Chili Salsa  1043.000000  1043  1043
Chips and Tomatillo-Red Chili Salsa    1043.000000  1043  1043
Crispy Tacos                              3.000000     2     4
Izze                                     78.400000     6   356
Nantucket Nectar                        282.555556     5   363
Salad                                   453.000000    10   896
Side of Chips                          1043.000000  1043  1043
Steak Bowl                              470.303318    20  1034
Steak Burrito                           506.084239    11  1027
Steak Crispy Tacos                      472.400000    32   983
Steak Salad                             692.250000   101   968
Steak Salad Bowl                        335.448276   121   750
Steak Soft Tacos                        484.545455    69  1020
Veggie Bowl                             454.752941    54  1015
Veggie Burrito                          413.200000    47  1013
Veggie Crispy Tacos                      86.000000    86    86
Veggie Salad                            856.833333   378  1013
Veggie Salad Bowl                       336.666667   157   725
Veggie Soft Tacos                       285.857143    48   724

#dataframe에서 groupby 이후 값의 비율 구하기

In [ ]:
result=df.groupby('item_name').choice_description.agg(['first', 'last', 'nunique'])
result

,first,last,nunique
item_name,,,
6 Pack Soft Drink,[Sprite],[Lemonade],5
Barbacoa Bowl,"[Roasted Chili Corn Salsa, [Fajita Vegetables,...","[Roasted Chili Corn Salsa, [Pinto Beans, Sour ...",49
Barbacoa Burrito,"[[Fresh Tomato Salsa (Mild), Tomatillo-Green C...",[Tomatillo Green Chili Salsa],71
Barbacoa Crispy Tacos,"[Tomatillo Red Chili Salsa, [Rice, Black Beans...","[[Fresh Tomato Salsa (Mild), Tomatillo-Green C...",11
Barbacoa Salad Bowl,"[Fresh Tomato Salsa, [Rice, Fajita Vegetables,...","[Tomatillo Green Chili Salsa, [Fajita Vegetabl...",9
Barbacoa Soft Tacos,"[Fresh Tomato Salsa, [Fajita Vegetables, Black...","[Roasted Chili Corn Salsa, [Fajita Vegetables,...",17
Bottled Water,None,None,0
Bowl,"[Braised Carnitas, Pinto Beans, [Sour Cream, C...","[Adobo-Marinated and Grilled Steak, [Sour Crea...",2
Burrito,"[Adobo-Marinated and Grilled Chicken, Pinto Be...","[White Rice, Adobo-Marinated and Grilled Steak...",6
Canned Soda,[Sprite],[Sprite],6
Canned Soft Drink,[Coke],[Sprite],5
Carnitas Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...","[Fresh Tomato Salsa, [Fajita Vegetables, Rice,...",59
Carnitas Burrito,"[[Tomatillo-Green Chili Salsa (Medium), Roaste...","[Tomatillo Green Chili Salsa, [Rice, Pinto Bea...",47
Carnitas Crispy Tacos,[Roasted Chili Corn Salsa],"[Fresh Tomato Salsa, [Pinto Beans, Sour Cream,...",7
Carnitas Salad,"[[Fresh Tomato Salsa (Mild), Roasted Chili Cor...","[[Fresh Tomato Salsa (Mild), Roasted Chili Cor...",1
Carnitas Salad Bowl,"[Fresh Tomato Salsa, [Rice, Black Beans, Chees...","[Tomatillo Green Chili Salsa, [Black Beans, Ch...",6
Carnitas Soft Tacos,"[Tomatillo Green Chili Salsa, [Fajita Vegetabl...","[Tomatillo Red Chili Salsa, [Fajita Vegetables...",28
Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...","[Fresh Tomato Salsa, [Rice, Black Beans, Chees...",348
Chicken Burrito,"[Tomatillo-Green Chili Salsa (Medium), [Pinto ...","[Fresh Tomato Salsa, [Fajita Vegetables, Rice]]",310
Chicken Crispy Tacos,"[Roasted Chili Corn Salsa, [Fajita Vegetables,...","[Tomatillo Red Chili Salsa, [Black Beans, Chee...",43
Chicken Salad,"[Roasted Chili Corn Salsa (Medium), [Black Bea...","[Roasted Chili Corn (Medium), [Lettuce, Black ...",7
Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...","[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",78
Chicken Soft Tacos,"[Roasted Chili Corn Salsa, [Rice, Black Beans,...","[Fresh Tomato Salsa, [Rice, Cheese, Sour Cream]]",78
Chips,None,None,0
Chips and Fresh Tomato Salsa,None,None,0
Chips and Guacamole,None,None,0
Chips and Mild Fresh Tomato Salsa,None,None,0
Chips and Roasted Chili Corn Salsa,None,None,0
Chips and Roasted Chili-Corn Salsa,None,None,0
Chips and Tomatillo Green Chili Salsa,None,None,0
Chips and Tomatillo Red Chili Salsa,None,None,0
Chips and Tomatillo-Green Chili Salsa,None,None,0
Chips and Tomatillo-Red Chili Salsa,None,None,0
Crispy Tacos,[Adobo-Marinated and Grilled Steak],[Adobo-Marinated and Grilled Chicken],2
Izze,[Clementine],[Blackberry],3
Nantucket Nectar,[Apple],[Peach Orange],4
Salad,"[Brown Rice, Adobo-Marinated and Grilled Chick...","[White Rice, Adobo-Marinated and Grilled Chick...",2
Side of Chips,None,None,0
Steak Bowl,"[Fresh Tomato Salsa (Mild), [Black Beans, Rice...","[Tomatillo Red Chili Salsa, [Rice, Black Beans...",155
Steak Burrito,"[Tomatillo Red Chili Salsa, [Fajita Vegetables...","[Fresh Tomato Salsa, [Rice, Sour Cream, Cheese...",251
Steak Crispy Tacos,"[Fresh Tomato Salsa, Sour Cream]","[Roasted Chili Corn Salsa, [Fajita Vegetables,...",28
Steak Salad,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...","[[Lettuce, Fajita Veggies]]",3
Steak Salad Bowl,"[Tomatillo Red Chili Salsa, [Black Beans, Chee...","[Fresh Tomato Salsa, [Fajita Vegetables, Lettu...",28
Steak Soft Tacos,"[Tomatillo Green Chili Salsa, [Pinto Beans, Ch...","[Tomatillo Green Chili Salsa, [Rice, Pinto Bea...",42
Veggie Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Rice,...","[Fresh Tomato Salsa, [Fajita Vegetables, Rice,...",62
Veggie Burrito,"[Tomatillo Red Chili Salsa, [Fajita Vegetables...","[Tomatillo Green Chili Salsa, [Rice, Fajita Ve...",58
Veggie Crispy Tacos,"[Fresh Tomato Salsa (Mild), [Pinto Beans, Rice...","[Fresh Tomato Salsa (Mild), [Pinto Beans, Rice...",1
Veggie Salad,"[[Fresh Tomato Salsa (Mild), Roasted Chili Cor...","[[Fresh Tomato Salsa (Mild), Roasted Chili Cor...",4
Veggie Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Rice,...","[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",16
Veggie Soft Tacos,"[Tomatillo Red Chili Salsa, [Fajita Vegetables...","[Fresh Tomato Salsa (Mild), [Black Beans, Rice...",7

In [ ]:
result.dropna(subset=['first'], inplace=True)
result

,first,last,nunique
item_name,,,
6 Pack Soft Drink,[Sprite],[Lemonade],5
Barbacoa Bowl,"[Roasted Chili Corn Salsa, [Fajita Vegetables,...","[Roasted Chili Corn Salsa, [Pinto Beans, Sour ...",49
Barbacoa Burrito,"[[Fresh Tomato Salsa (Mild), Tomatillo-Green C...",[Tomatillo Green Chili Salsa],71
Barbacoa Crispy Tacos,"[Tomatillo Red Chili Salsa, [Rice, Black Beans...","[[Fresh Tomato Salsa (Mild), Tomatillo-Green C...",11
Barbacoa Salad Bowl,"[Fresh Tomato Salsa, [Rice, Fajita Vegetables,...","[Tomatillo Green Chili Salsa, [Fajita Vegetabl...",9
Barbacoa Soft Tacos,"[Fresh Tomato Salsa, [Fajita Vegetables, Black...","[Roasted Chili Corn Salsa, [Fajita Vegetables,...",17
Bowl,"[Braised Carnitas, Pinto Beans, [Sour Cream, C...","[Adobo-Marinated and Grilled Steak, [Sour Crea...",2
Burrito,"[Adobo-Marinated and Grilled Chicken, Pinto Be...","[White Rice, Adobo-Marinated and Grilled Steak...",6
Canned Soda,[Sprite],[Sprite],6
Canned Soft Drink,[Coke],[Sprite],5
Carnitas Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...","[Fresh Tomato Salsa, [Fajita Vegetables, Rice,...",59
Carnitas Burrito,"[[Tomatillo-Green Chili Salsa (Medium), Roaste...","[Tomatillo Green Chili Salsa, [Rice, Pinto Bea...",47
Carnitas Crispy Tacos,[Roasted Chili Corn Salsa],"[Fresh Tomato Salsa, [Pinto Beans, Sour Cream,...",7
Carnitas Salad,"[[Fresh Tomato Salsa (Mild), Roasted Chili Cor...","[[Fresh Tomato Salsa (Mild), Roasted Chili Cor...",1
Carnitas Salad Bowl,"[Fresh Tomato Salsa, [Rice, Black Beans, Chees...","[Tomatillo Green Chili Salsa, [Black Beans, Ch...",6
Carnitas Soft Tacos,"[Tomatillo Green Chili Salsa, [Fajita Vegetabl...","[Tomatillo Red Chili Salsa, [Fajita Vegetables...",28
Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...","[Fresh Tomato Salsa, [Rice, Black Beans, Chees...",348
Chicken Burrito,"[Tomatillo-Green Chili Salsa (Medium), [Pinto ...","[Fresh Tomato Salsa, [Fajita Vegetables, Rice]]",310
Chicken Crispy Tacos,"[Roasted Chili Corn Salsa, [Fajita Vegetables,...","[Tomatillo Red Chili Salsa, [Black Beans, Chee...",43
Chicken Salad,"[Roasted Chili Corn Salsa (Medium), [Black Bea...","[Roasted Chili Corn (Medium), [Lettuce, Black ...",7
Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...","[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",78
Chicken Soft Tacos,"[Roasted Chili Corn Salsa, [Rice, Black Beans,...","[Fresh Tomato Salsa, [Rice, Cheese, Sour Cream]]",78
Crispy Tacos,[Adobo-Marinated and Grilled Steak],[Adobo-Marinated and Grilled Chicken],2
Izze,[Clementine],[Blackberry],3
Nantucket Nectar,[Apple],[Peach Orange],4
Salad,"[Brown Rice, Adobo-Marinated and Grilled Chick...","[White Rice, Adobo-Marinated and Grilled Chick...",2
Steak Bowl,"[Fresh Tomato Salsa (Mild), [Black Beans, Rice...","[Tomatillo Red Chili Salsa, [Rice, Black Beans...",155
Steak Burrito,"[Tomatillo Red Chili Salsa, [Fajita Vegetables...","[Fresh Tomato Salsa, [Rice, Sour Cream, Cheese...",251
Steak Crispy Tacos,"[Fresh Tomato Salsa, Sour Cream]","[Roasted Chili Corn Salsa, [Fajita Vegetables,...",28
Steak Salad,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...","[[Lettuce, Fajita Veggies]]",3
Steak Salad Bowl,"[Tomatillo Red Chili Salsa, [Black Beans, Chee...","[Fresh Tomato Salsa, [Fajita Vegetables, Lettu...",28
Steak Soft Tacos,"[Tomatillo Green Chili Salsa, [Pinto Beans, Ch...","[Tomatillo Green Chili Salsa, [Rice, Pinto Bea...",42
Veggie Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Rice,...","[Fresh Tomato Salsa, [Fajita Vegetables, Rice,...",62
Veggie Burrito,"[Tomatillo Red Chili Salsa, [Fajita Vegetables...","[Tomatillo Green Chili Salsa, [Rice, Fajita Ve...",58
Veggie Crispy Tacos,"[Fresh Tomato Salsa (Mild), [Pinto Beans, Rice...","[Fresh Tomato Salsa (Mild), [Pinto Beans, Rice...",1
Veggie Salad,"[[Fresh Tomato Salsa (Mild), Roasted Chili Cor...","[[Fresh Tomato Salsa (Mild), Roasted Chili Cor...",4
Veggie Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Rice,...","[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",16
Veggie Soft Tacos,"[Tomatillo Red Chili Salsa, [Fajita Vegetables...","[Fresh Tomato Salsa (Mild), [Black Beans, Rice...",7